# Generated by Django 4.1.7 on 2023-09-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
