# Generated by Django 5.0.6 on 2024-07-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='disliked',
            field=models.BooleanField(default=False, verbose_name='Дизлайкнул курс'),
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='liked',
            field=models.BooleanField(default=False, verbose_name='Лайкнул курс'),
        ),
    ]
