# Generated by Django 5.0.6 on 2024-07-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
