# Generated by Django 5.0.6 on 2024-06-21 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['-created'], name='actions_act_created_64f10d_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['target_ct', 'target_id'], name='actions_act_target__f20513_idx'),
        ),
    ]
