# Generated by Django 4.1.7 on 2023-07-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, verbose_name='Слаг'),
        ),
    ]
