# Generated by Django 4.1.7 on 2023-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_cards_card_id_7c40cb_idx_and_more'),
        ('lesson', '0002_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='cards',
            field=models.ManyToManyField(blank=True, to='cards.card'),
        ),
    ]
