# Generated by Django 4.1.7 on 2023-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['id', 'slug'], name='cards_card_id_7c40cb_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['term'], name='cards_card_term_859d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['definition'], name='cards_card_definit_0aec54_idx'),
        ),
    ]
